lcy2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^splitter/', include('splitter.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^social-auth/', include('social_django.urls', namespace='social')),
    url(r'^login/$', login, {'template_name': 'splitter/login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^$', TemplateView.as_view(template_name = "lcy2/place_holder.html"), name='home'),
]

splitter/urls.py
from django.conf.urls import url
from . import views, gateway

app_name = "splitter"
urlpatterns = [
    url(r'^gateway/(?P<action>[a-z]+)$', views.gateway_switch, name = 'gateway'),
    url(r'^outward$', views.outward, name = 'outward'),
    url(r'^$', views.index, name = 'index'),
    url(r'^(?P<pk>[0-9]+)$', views.trip_overview, name = 'trip_overview'),
    url(r'^(?P<pk>[0-9]+)/trip_edit$', views.trip_edit, name = 'trip_edit'),
    url(r'^(?P<pk>[0-9]+)/display$', views.phototrek, name = 'phototrek'),
    url(r'^(?P<pk>[0-9]+)/phototrek_edit$', views.phototrek_edit, name = 'phototrek_edit'),
    url(r'^(?P<pk>[0-9]+)/charges$', views.charges, name = 'trip_charges'),
    url(r'^(?P<pk>[0-9]+)/charges/(?P<hash_val>[-0-9]+)$', views.published_charges, name='public_charge_url'),
    url(r'^(?P<pk>[0-9]+)/itinerary$', views.itinerary, name = 'trip_itinerary'),
    url(r'^(?P<pk>[0-9]+)/itinerary/(?P<hash_val>[-0-9]+)$', views.published_itinerary, name='public_itinerary_url'),
    url(r'^(?P<pk>[0-9]+)/edit_currencies$', views.edit_currencies, name = 'edit_currencies'),
    url(r'^(?P<pk>[0-9]+)/init_charges$', gateway.init_charges, name = 'init_charges'),
    url(r'^(?P<trav>[a-zA-z]+)/display$', views.traveler, name = 'traveler'),
    url(r'^newtrip$', views.new_trip, name = 'new_trip'),
    url(r'^newtrip2$', gateway.new_trip, name = 'new_trip2'),
    url(r'^tripplan$', views.trip_plan, name="trip_plan"),
    url(r'^debug$', views.debug, name="debug"),
]

splitter/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.urls import reverse

from datetime import date


class Traveler(models.Model):
    """ An intermediate between a user object and a traveler registered to each trip"""
    user = models.OneToOneField(User, blank = True, null = True, on_delete = models.CASCADE)
    traveler_name = models.CharField(max_length = 50, default = "Unknown")

    def __repr__(self):
        return self.traveler_name

    def __str__(self):
        return repr(self)

    def get_absolute_url(self):
        return reverse('splitter:traveler', kwargs={'trav': self.traveler_name})


def charge_json_default():
    return {
        'charges': dict(),
        'currencies': list(),
        'is_private': True,
        'n_charges': 0,
        'order': list(),
    }

def itinerary_json_default():
    return {
        'itinerary': dict(), # each entry contains {date: date, lodging: URL | "" | "inherit", transport: URL | "", segment: str, description: str }
        'is_private': True,
    }

class Trip(models.Model):
    # name of the trip
    trip_name = models.CharField(max_length = 50, default = "Unname Trip")
    trip_description = models.CharField(max_length = 300, blank = True)
    # comma-separated names of travelers
    travelers = models.ManyToManyField(Traveler)
    trip_start = models.DateField(default=date.today)
    trip_end = models.DateField(default=date.today)
    time_modified = models.DateTimeField(auto_now = True)
    time_created = models.DateTimeField(auto_now_add = True)
    profile_pic = models.URLField(default = 'https://unsplash.it/200/300?image=1039')
    profile_misc = JSONField(blank = True, null = True, default = dict)
    authorized_viewers = models.ManyToManyField(User, blank = True)
    is_private = models.BooleanField(default = True)
    accounting = JSONField(default = charge_json_default)
    itinerary = JSONField(default = itinerary_json_default)

    def __repr__(self):
        return unicode(self.trip_name)

    def __unicode__(self):
        return repr(self)

    def get_absolute_url(self):
        return reverse('splitter:trip_overview', kwargs={'pk': self.pk})



class Segment(models.Model):
    trip = models.ForeignKey(Trip, on_delete = models.CASCADE)
    segment_name = models.CharField(max_length = 50)
    segment_start = models.DateField(blank = True, null = True)
    segment_end = models.DateField(blank = True, null = True)
    segment_lng = models.FloatField(blank = True, null = True)
    segment_lat = models.FloatField(blank = True, null = True)
    segment_img = models.URLField(blank = True)
    segment_album = models.CharField(max_length = 30, blank = True)
    segment_detail = JSONField(blank = True, null = True, default = dict)

    def __unicode__(self):
        return self.segment_name

splitter/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.urls import reverse

from social_django.models import UserSocialAuth

from .models import Trip, Segment, Traveler
from . import gateway
from .decorators import check_trip_access
from .utils import process_charge, trip_hash

from lxml import objectify
from urllib import urlencode
from decouple import config

import requests, time, json, re

# Create your views here.

def index(request):
    user = request.user
    private_trips = []
    if user and not user.is_anonymous():
        try:
            private_trips = (user.traveler.trip_set.all() | user.trip_set.all()).distinct().order_by('trip_start')
        except ObjectDoesNotExist:
            pass

    public_trips = Trip.objects.filter(is_private = False).order_by('trip_start')

    context = {
        'private_trips': private_trips,
        'public_trips' : public_trips,
    }

    return render(request, 'splitter/index.html', context)


def gateway_switch(request, action):
    action_dir_trip = {
        'rtfg': gateway.refresh_trek_from_google,
        'rafd': gateway.read_albums_from_db,
        'rpfd': gateway.read_pics_from_db,
        'etd': gateway.edit_trip_info,
        'gpio': gateway.get_preview_info_only,
        'newcharge': gateway.new_charge,
        'delcharge': gateway.del_charge,
        'swapcharge': gateway.swap_charge,
        'sumcharge': gateway.charge_summary,
        'privcharge': gateway.charge_privacy_toggle,
        'ec': gateway.edit_currencies,
    }
    action_dir_seg = {
        'picedits': gateway.pic_edits,
        'picdel': gateway.pic_delete,
        'setcover': gateway.set_album_cover,
    }
    action_dir = {
        'newtrav': gateway.new_traveler,
    }
    if action in action_dir_trip:
        if 'HTTP_REFERER' in request.META:
            p = re.compile(r'(?<=\/)[0-9]+(?=[\/#]|$)')
            pk = int(p.search(request.META['HTTP_REFERER']).group())
            return action_dir_trip[action](request, pk)
        else:
            return JsonResponse({'message': 'Went down the wrong rabbit hole.'}, status = 400)
    elif action in action_dir_seg:
        seg_pk = None
        if 'pk[]' in request.POST:
            seg_pk = map(int, request.POST.getlist('pk[]'))
        elif 'pk' in request.POST:
            seg_pk = [request.POST['pk']]
        else:
            return JsonResponse({'message': 'Invalid request. No album identifier supplied.'}, status = 400)

        if not seg_pk:
            return JsonResponse({'message': 'Album does not exist.'}, status = 404)

        seg = Segment.objects.filter(pk__in = seg_pk)
        pk = seg[0].trip.pk;
        return action_dir_seg[action](request, pk, seg = seg)

    elif action in action_dir:
        return action_dir[action](request)

    messages.error(request, "Went down the wrong rabbit hole.")
    return redirect("splitter:index")

@check_trip_access(False)
def trip_overview(request, trip, editable):
    if not editable:
        return redirect('splitter:phototrek', pk = trip.pk)

    context = {
        'trip': trip,
        'edit_permission': editable,
    }
    return render(request, 'splitter/trip_overview.html', context)

@check_trip_access(True)
def trip_edit(request, trip, editable):
    context = {
        'trip': trip,
        'edit_permission': editable,
    }
    return render(request, 'splitter/trip_edit.html', context)

# adapted from https://github.com/morganwahl/photos-db/blob/master/photosdb/photosdb/views.py
@check_trip_access(True)
def phototrek_edit(request, trip, editable):
    """ return all albums """
    refresh_buttons = dict()
    try:
        google_social = request.user.social_auth.get(provider='google-oauth2')
        refresh_buttons['google'] = True
    except UserSocialAuth.DoesNotExist:
        refresh_button['google'] = False

    if not any(refresh_buttons.values()):
        messages.error(request, "You do not have linked social accounts.")
        return redirect("splitter:index")

    context = {
        'trip': trip,
        'refresh_buttons': refresh_buttons,
        'edit_permission': editable,
        'path': request.path,
    }

    # determine whether additional Google access is needed
    if refresh_buttons['google']:
        # True indicates that access token has the right scope
        google_photo_scope = 'scope' in google_social.extra_data and \
            "https://picasaweb.google.com/data/" in google_social.extra_data['scope'] and \
            "https://photos.googleapis.com/data/" in google_social.extra_data['scope']
        context.update({'google_photo_scope': google_photo_scope})

    return render(request, 'splitter/phototrek_edit.html', context)

@check_trip_access(False)
def phototrek(request, trip, editable):
    context = {
        'trip': trip,
        'edit_permission': editable,
    }
    return render(request, 'splitter/phototrek_display.html', context)

@login_required
def new_trip(request):
    try:
        request.user.traveler
    except ObjectDoesNotExist:
        trav = Traveler(user=request.user, traveler_name = request.user.first_name if request.user.first_name else request.user.username)
        trav.save()

    context = {
        'travelers': Traveler.objects.all()
    }
    return render(request, 'splitter/new_trip.html', context)

def trip_plan(request):
    return render(request, 'splitter/trip_plan.html', {})


# legacy mapbox json calls
@login_required
def outward(request):
    if 'target' not in request.GET:
        return JsonResponse({'message': 'Unknown request.', 'warning_level': 'warning'}, status = 400)

    def mapbox_tsp():
        params = ['latlon_string', 'access_token', 'mode']
        if not all([p in request.GET for p in params]):
            return JsonResponse({'message': 'Missing parameters.'}, status = 400)
        url = 'https://api.mapbox.com/optimized-trips/v1/mapbox/' + request.GET['mode'] + '/' + request.GET['latlon_string']
        query = {
            'access_token': request.GET['access_token'],
            'geometries': 'geojson',
            'overview': 'full',
            'roundtrip': request.GET['roundtrip'] if 'roundtrip' in request.GET else 'true',
            'source': 'first',
            'destination': 'last',
        }
        url += '?' + urlencode(query)
        return requests.get(url).json()

    def mapbox_dir():
        params = ['latlon_string', 'access_token', 'mode']
        if not all([p in request.GET for p in params]):
            return JsonResponse({'message': 'Missing parameters.'}, status = 400)
        url = 'https://api.mapbox.com/directions/v5/mapbox/' + request.GET['mode'] + '/' + request.GET['latlon_string']
        query = {
            'access_token': request.GET['access_token'],
            'geometries': 'geojson',
        }
        url += '?' + urlencode(query)
        return requests.get(url).json()

    def mapbox_rgeo():
        params = ['latlon_string', 'access_token']
        if not all([p in request.GET for p in params]):
            return JsonResponse({'message': 'Missing parameters.'}, status = 400)
        url = 'https://api.mapbox.com/geocoding/v5/mapbox.places/' + request.GET['latlon_string'] + '.json'
        query = {
            'access_token': request.GET['access_token'],
        }
        url += "?" + urlencode(query)
        return requests.get(url).json()

    outward_action = {
        'mapbox_tsp': mapbox_tsp,
        'mapbox_dir': mapbox_dir,
        'mapbox_rgeo': mapbox_rgeo,
    }

    return JsonResponse(outward_action[request.GET['target']]())


def traveler(request, trav):
    try:
        traveler = Traveler.objects.get(traveler_name = trav)
    except ObjectDoesNotExist:
        messages.warning("traveler doesn't exist.")
        return redirect('splitter:index')

    user = request.user
    trips = traveler.trip_set.filter(is_private= False)
    if user and not user.is_anonymous():
        trips = (user.traveler.trip_set.all() | user.trip_set.all() & traveler.trip_set.all() | trips).distinct()

    if not trips:
        messages.warning("No viewable trips available.")
        return redirect('splitter:index')

    context = {
        'traveler': traveler,
        'trips': trips,
    }

    return render(request, 'splitter/traveler.html', context)

@check_trip_access(True)
def charges(request, trip, editable):
    # if there are no records in charges
    # redirect to the page for creating the initial sets of parameters
    if not trip.accounting['currencies']:
        # get list of currencies from openexchangerate
        url = 'https://openexchangerates.org/api/latest.json?app_id=' + config('OXR_API_KEY')
        rates = requests.get(url).json()['rates']
        url = 'https://openexchangerates.org/api/currencies.json'
        currencies = [(abbrev, 1 / float(rates[abbrev]), full_name) for abbrev, full_name in requests.get(url).json().iteritems()]
        context = {
            'trip': trip,
            'currencies': currencies,
        }
        return render(request, 'splitter/new_charges.html', context)

    # process charges into strings
    travelers = trip.travelers.all().order_by('pk')
    charges = process_charge(trip, travelers, trip.accounting['charges'], trip.accounting['order'])
    context = {
        'trip': trip,
        'charges': charges,
        'travelers': travelers,
        'currencies': trip.accounting['currencies'],
        'editable': editable,
        'share_url': '' if trip.accounting['is_private'] else request.build_absolute_uri(reverse("splitter:public_charge_url", kwargs={'pk':trip.pk, 'hash_val':trip_hash(trip,'charge')})),
    }
    return render(request, 'splitter/trip_charges.html', context)

splitter/templates/splitter/edit_currencies.html
{% extends 'splitter/trip_base.html' %}
{% load static %}
{% block trip_base %}
  <form action="{% url 'splitter:gateway' action='ec' %}" method="post">
    <div class="container-fluid">
      <div class="page-header">
        <h1>Edit Exchange Rates</h1>
      </div>
      <div class="row">
      {% csrf_token %}
      {% for currency in currencies %}
        <div class="col-sm-6 col-md-4 col-lg-3">
          <div class="form-group">
            <label class="control-label">{{currency.abbr}} <small>{{currency.name}}</small></label>
            <div class="input-group">
              <input class="c_input form-control" type="text" name="currencies" value="{{currency.custom_xrate}}"></input>
              <span class="input-group-addon">vs. {{currency.xrate}}</span>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
      <div class="row">
        <div class="col-xs-8">
          <span class="label label-default">Conversions are in USD</span>
          <span class="label label-default">Formal rates are shown as reference.</span>
        </div>
        <div class="col-xs-4 text-right">
            <button type="submit" class="btn btn-primary">Submit</button>

        </div>
      </div>
    </div>
  </form>
{% endblock %}

{% block trip_override %}
  <script src="{% static 'exlibs/anime.min.js' %}"></script>
  <script src="{% static 'splitter/splitter-edit-currencies.js' %}"></script>
  <link rel="stylesheet" href="{% static 'splitter/splitter-edit-currencies.css' %}" />
{% endblock %}

splitter/templates/splitter/editable_palette.html
<div class="container-fluid">
  <div class="row spacey_row">
    <div class="col-sm-4">
      <a href="{% url 'splitter:trip_edit' pk=trip.id %}" role="button" class="btn btn-primary btn-block">Manage Trip Details</a>
    </div>
    <div class="col-sm-4">
      <a href="{% url 'splitter:phototrek_edit' pk=trip.id %}" role="button" class="btn btn-primary btn-block">Manage Your PhotoTrail</a>
    </div>
    <div class="col-sm-4">
      <a href="{% url 'splitter:trip_charges' pk=trip.id %}" role="button" class="btn btn-primary btn-block">View/Edit Expenses</a>
    </div>

  </div>
</div>

splitter/templates/splitter/loading_screen.html
{% load static %}
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
<div id="loading">
  <div class="spinner">
    <div class="dot1"></div>
    <div class="dot2"></div>
  </div>
  <div id="loading_msg">{{ loading_msg }}</div>
</div>
<link rel="stylesheet" type="text/css" href="{% static 'splitter/splitter-loading-screen.css' %}" />
<script src="{% static 'splitter/splitter-loading-screen.js' %}"></script>

splitter/templates/splitter/new_charges.html
{% extends 'splitter/base.html' %}
{% load static %}
{% block main %}
  <div class="container bordered_container">
    <form action="{% url 'splitter:init_charges' pk=trip.pk %}" method="post">
      {% csrf_token %}
      <div class="container-fluid">
        <div class="page-header">
          <h1>Select Currencies</h1>
        </div>
        <div class="row">
          <div class="form-group col-sm-9">
            <label class="control-label">Currencies: </label>
            <select name="currencies" title="Select Currencies" class="selectpicker" data-size="7" multiple data-selected-text-format="count>2" data-count-selected-text="{0} Currencies" data-live-search="true">
              {% for abbrev, rate, full_name in currencies %}
                <option value="{{full_name}}:{{ abbrev }}:{{rate}}" data-tokens="{{full_name}} {{abbrev}}" data-subtext="{{full_name}}">{{abbrev}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-sm-3">
            <div class="pull-right">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

{% block override %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css" />
  <script src="{% static 'splitter/splitter-new-charges.js' %}"></script>
{% endblock %}

splitter/templates/splitter/test.html
{% for post in posts %}
  <p>{{ post }}</p>
{% endfor %}
{% for get in gets %}
  <p>{{ get }}</p>
{% endfor %}

splitter/templates/splitter/trip_charges.html
{% extends 'splitter/trip_base.html' %}
{% load static %}
{% block trip_base %}
{% csrf_token %}

  <div class="page-header">
    <h1>Accounting</h1>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">Details</div>
    <div class="list-group" id="sortable_list">
      {% for charge in charges %}
      <div>
        <div class="list-group-item clearfix" title="{{ charge.footnote }}" data-hash="{{charge.hash_val}}">
          {% if editable %}<span class="glyphicon glyphicon-resize-vertical"></span>{% endif %}
          <span class="label label-default">{{charge.time}}</span>&nbsp;<span class="label progress-bar-flat-{{charge.payer.index}} payer_name">{{charge.payer.name}}</span>
            <span> paid <u><strong>{{charge.amount}}</strong></u> for {{charge.description}}.</span><small>{{ charge.footnote }}</small>
          {% if editable %}
            <div class="pull-right">
              <span class="glyphicon glyphicon-edit"></span><span class="glyphicon glyphicon-trash"></span>
            </div>
          {% endif %}
        </div>
        <div class="progress">
          {% for trav_index, portion, amt, trav_name in charge.breakdown %}
            <div class="progress-bar progress-bar-flat-{{trav_index}}" role="progressbar" style="width:{{portion}}%">
              <span class="progress_annotation">{{trav_name}}: {{amt}}</span>
            </div>
          {% endfor %}
        </div>
      </div>
      {% endfor %}
    </div>

    <div class="panel-footer text-right">
      {% if editable %}
        {% if currencies|length > 1 %}
        <a role="button" class="btn btn-primary" href="{% url 'splitter:edit_currencies' pk=trip.pk %}">Edit Exchange Rates</a>
        {% endif %}
      {% endif %}
      <a id="summary_btn" role="button" class="btn btn-primary" href="#summary" data-lity>Summary</a>
    </div>
  </div>

  {% if editable %}
    <div class="container-fluid" id="new_charge_form">
      <div class="row">
        <div class="col-xs-6 col-sm-4 col-md-3">
          <div class="input-group">
            <select id="pay_select" name="payer" title="Who" class="selectpicker form-control" data-size="4">
              {% for traveler in travelers %}
                <option value="{{traveler.pk}}">{{traveler.traveler_name}}</option>
              {% endfor %}
            </select>
            <span class="input-group-addon">paid</span>
          </div>
        </div>
        <div class="col-xs-6 col-sm-4 col-md-3">
          <div class="input-group">
            <span class="input-group-addon">for</span>
            <select id="debt_select" name="debtors" title="whom" class="selectpicker form-control" multiple data-size="4" data-actions-box="true">
              {% for traveler in travelers %}
                <option value="{{traveler.pk}}">{{traveler.traveler_name}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-3">
          <div class="input-group">
            <input name="amount" id="amt" placeholder="how much" class="form-control" type="text" value="0.00"></input>
            <div class="input-group-btn">
              <select id="currency" name="currencies" class="selectpicker form-control" data-size="4" data-width="70px">
                {% for currency in currencies %}
                  <option name="currency" value="{{forloop.counter0}}"{% if forloop.first %} selected{% endif %}>{{currency.abbr}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
        </div>
        <div class="col-sm-4 col-md-3">
          <div class="input-group date">
            <input type="text" id="time_input" name="time" readonly class="form-control" placeholder="when"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
          </div>
        </div>
        <div class="col-sm-4 col-md-3">
          <div id="radio_grp">
            <div class="input-group" id="even_grp">
              <div class="input-group-addon">
                <input type="radio" name="distribution" value="even" checked aria-label="even" />
              </div>
              <div class="input-group-btn">
                <button type="button" class="btn btn-default" id="even_btn">Even</button>
              </div>
            </div>
            <div class="input-group" id="itemize_grp">
              <div class="input-group-addon">
                <input type="radio" name="distribution" value="itemized" aria-label="itemized" />
              </div>
              <div class="dropdown input-group-btn">
                <button class="btn btn-default dropdown-toggle" type="button" id="itemizing" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Itemize <span class="caret"></span></button>
                <ul class="dropdown-menu" aria-labelledby="itemize-dropdown" id="itemize_dropdown">
                </ul>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4 pull-right">
          <div class="input-group pull-right" id="tt_grp">
            <div class="input-group-addon">
              <input type="checkbox" name="taxandtip" id="tt_check" />
            </div>
            <span class="input-group-addon">Tax &amp; Tip</span>
            <input class="form-control" type="text" id="tt_amt" size="4" maxlength="4" value="25" />
            <span class="input-group-addon">%</span>
          </div>
        </div>
      </div>

      <div class="input-group">
        <span class="input-group-addon">What for?</span>
        <input name="description" type="text" class="form-control" id="descriptor"></input>
        <div class="input-group-btn">
          <button id="submit" class="btn btn-primary" type="button">Submit</button>
        </div>
      </div>

      <div class="input-group" id="is_private">
        <div class="input-group-btn">
          <input type="checkbox" id="is_private_btn" data-toggle="toggle" data-on="Public" data-off="Private" data-size="small" {% if not trip.accounting.is_private %}checked{% endif %}></input>
        </div>
        <input type="text" id="share_url" class="form-control input-sm" readonly value="{{share_url}}"></input>
      </div>
    </div>
  {% endif %}

  <div id="summary" class="container lity-hide">
    {% for traveler in travelers %}
      <div class="panel panel-default" id="traveler-{{traveler.pk}}">
        <div class="panel-heading">{{traveler.traveler_name}}<div class="pull-right"><span class="total_amt"></span>&nbsp;<span class="lity_currency"></span></div></div>
        <div class="panel-body">
          <div class="spending">
            <span class="label label-default">Spending: </span><small class="pull-right"><span class="total_amt"></span>&nbsp;<span class="lity_currency"></span></small>
            <div class="progress"></div>
          </div>
          <div class="payment">
            <span class="label label-default">Payment: </span><small class="pull-right"><span class="total_amt"></span>&nbsp;<span class="lity_currency"></span></small>
            <div class="progress"></div>
          </div>
        </div>
      </div>
    {% endfor %}
    <select id="lity_currency_select" class="selectpicker form-control pull-right" data-size="4" data-width="70px">
      {% for currency in currencies %}
        <option name="currency" value="{{currency.custom_xrate}}"{% if forloop.first %} selected{% endif %}>{{currency.abbr}}</option>
      {% endfor %}
    </select>
  </div>
{% endblock %}

{% block trip_override %}
  {% if editable %}
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker3.min.css" integrity="sha256-nFp4rgCvFsMQweFQwabbKfjrBwlaebbLkE29VFR0K40=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js" integrity="sha256-urCxMaTtyuE8UK5XeVYuQbm/MhnXflqZ/B9AOkyTguo=" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/Sortable/1.6.0/Sortable.min.js"></script>
  {% endif %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css" />
  <script src="{% static 'exlibs/anime.js' %}"></script>
  <script src="{% static 'exlibs/lity.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'exlibs/lity.min.css' %}" />
  <link rel="stylesheet" href="{% static 'splitter/splitter-trip-charges.css' %}" />
  <script src="{% static 'splitter/splitter-trip-charges.js' %}"></script>
  {% if editable %}
    <script src="{% static 'splitter/splitter-trip-charges-edit.js' %}"></script>
  {% endif %}
  <link rel="stylesheet" href="{% static 'splitter/splitter-custom-progress-bars.css' %}" />
{% endblock %}